services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8900
    restart: unless-stopped
