services:
  eviaboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - ORIGIN=0.0.0.0
      - HOST=0.0.0.0
      - PORT=8900
    restart: unless-stopped
